services:
  - type: web
    name: hobikecil-ecom
    runtime: docker
    plan: starter
    healthCheckPath: /health
    
    envVars:
      - key: APP_ENV
        value: production
      
      - key: APP_DEBUG
        value: "false"
      
      - key: LOG_CHANNEL
        value: stack
      
      - key: DB_CONNECTION
        value: mysql
      
      - key: DB_HOST
        value: eccomercehobikecil64-joseph-2246.h.aivencloud.com
      
      - key: DB_PORT
        value: "25044"
      
      - key: DB_USERNAME
        value: avnadmin
      
      - key: DB_PASSWORD
        # Set this in Render Dashboard Environment Variables
        value: ${DB_PASSWORD}
      
      - key: DB_DATABASE
        value: defaultdb
      
      - key: QUEUE_CONNECTION
        value: database
      
      - key: SESSION_DRIVER
        value: database
      
      - key: CACHE_STORE
        value: database
      
      - key: BROADCAST_CONNECTION
        value: log
